Start
Beginning script plots_v4.py
Beginning script...
Module loading completed.

 * Reading in data.../oak/stanford/groups/smontgom/amarder/t21-proj//oak/stanford/groups/smontgom/amarder/data/t21/ScanpyObjects/10X_DownSyndrome_Femur.h5ad
Traceback (most recent call last):
  File "plots_v4.py", line 45, in <module>
    adata=sc.read_h5ad(foutpath)
  File "/home/amarder/anaconda3/envs/minimal_env/lib/python3.6/site-packages/anndata/_io/h5ad.py", line 408, in read_h5ad
    with h5py.File(filename, "r") as f:
  File "/home/amarder/anaconda3/envs/minimal_env/lib/python3.6/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/home/amarder/anaconda3/envs/minimal_env/lib/python3.6/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = '/oak/stanford/groups/smontgom/amarder/t21-proj//oak/stanford/groups/smontgom/amarder/data/t21/ScanpyObjects/10X_DownSyndrome_Femur.h5ad', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
